# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 089935d2c9747de439dda4da24ebfa78935558b1168cabd210e0425b8340eb3188f8664a9ecb826ff37a2f48662cf4758b17284005b6d17cca59245fe62a4f39

test:
  secret_key_base: 2e060d62b9b3cbfdc9025ec89b578dd488de72c852a5b12a0ae04440d5db6f771e7cf3941e265a666049fefe9b380088cab1a596b108348e85d75c54edac8c33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
